---
title: "Bayesian Workflow book: Case studies"
date: 2026-01-05
date-modified: today
date-format: iso
format:
  html:
    number-sections: false
---

## Introduction

The code and data are provided to fully reproduce the examples and
figures in the book.  They can be a good way to see what the code
does. Different people have different styles of code and we don't
claim our style is the best.

When running the notebooks, to avoid the need to switch the working
directory, the `rprojroot` package is used to set the project root
directory. The downloaded git repository can be placed anywhere you
like and you can rename the Bayesian-Workflow directory if you
wish. When running the code, it is sufficient that the working
directory is any directory in the Bayesian-Workflow (or
renamed). Running
```
library("rprojroot")
root<-has_file(".Bayesian-Workflow-root")$make_fix_file()
```
will find the file `.Bayesian-Workflow-root` which is in the `Bayesian-Workflow` directory, 
and will set the full path according to that. Then, for example,
```
bioassay_stan_file <- root("bioassay","bioassay0.stan")
```
finds the `bioassay0.stan` file, no matter where you have placed or renamed the `Bayesian-Workflow` directory. When you switch to another example, there is no need to switch the working directory.


## Case studies

- [Sec 3.5: Bioassay](bioassay/bioassay.html)
- [Ch 4: Modeling performance on a multiple choice exam](multiple_choice/multiple_choice.html)
- [Sec 11.4-6: How many iterations to run and how many digits to report](digits/digits.html)
- [Sec 12.3: Illustration of problematic posteriors](problems/problems.html)
- [Sec 12.4: Declining exponentials](declining_exponentials/declining_exponentials.html)
- [Ch 16: Simulated data of movie ratings](movies/movies.html)
- [Ch 17: Sleep study: Prior specification and model checking](sleep_study/sleep_study.html)
- [Ch 18: Nabiximols treatment efficiency](nabiximols/nabiximols.html)
- [Ch 19: Sensitivity and specificity in coronavirus testing](coronavirus/coronavirus.html)
- [Ch 20: Mixture model for time series competition](timeseries/timeseries.html)
- [Ch 21: Stochastic learning in dogs -- brms version](dogs/dogs.html)
- [Ch 21: Stochastic learning in dogs -- Stan version](dogs/dogs_stan.html)
- [Ch 22: Survival analysis and black cat adoptions](cat_adoptions/cat_adoptions.html)
- [Ch 23: World Cup continuous vs discrete models](world_cup/world_cup.html)
- [Ch 24: Roaches cross-validation model checking and comparison](roaches/roaches.html)
- [Ch 25: Model building and expansion for golf putting](golf/golf.html)
- [Ch 26: Sharks and model building with latent variables](sharks/sharks.html)
- [Ch 27: Birthdays and time-series decomposition](birthdays/birthdays.html)
- [Ch 28: Variable selection](variable_selection/variable_selection.html)
- [Ch 29: Park rule: No vehicles in the park](park_rule/park_rule_aki.html)
- [Ch 30: Planetary motion: Computational challenge of multimodality](planetary_motion/planetary_motion.html)
- [Ch 31: Simulation based calibration checking (SBC)](sbc/sbc.html)


## Miscellaneous code

Code that is not part of complete case studies, but may be useful for 
regenerating some figures in Chapters 6--12, can be found in the [GitHub `misc` directory](https://github.com/avehtari/Bayesian-Workflow/tree/main/misc).


## Software versions

We list here all the software packages used in the case studies and the versions used
when rendering the case study web pages 2026-01-08.

```{r, echo=FALSE}
# 1. Find all .R files recursively
r_files <- list.files(
  path = ".",
  pattern = "\\.[Rr]$",
  recursive = TRUE,
  full.names = TRUE
)

# 2. Extract package names from each file
get_pkgs_from_file <- function(file) {
  txt <- readLines(file, warn = FALSE)
  # remove comments
  txt <- gsub("#.*$", "", txt)
  # collapse to single string for easier regex matching
  all_code <- paste(txt, collapse = "\n")
  pkgs <- character()
  # library(pkg) and require(pkg)
  lib_req_pattern <- "\\b(library|require)\\s*\\(\\s*(['\"]?)([A-Za-z0-9\\.]+)\\2\\s*\\)"
  lib_req_matches <- gregexpr(lib_req_pattern, all_code, perl = TRUE)
  if (lib_req_matches[[1]][1] != -1) {
    m <- regmatches(all_code, lib_req_matches)[[1]]
    pkgs <- c(pkgs, sub(lib_req_pattern, "\\3", m, perl = TRUE))
  }
  # pkg::fun or pkg:::fun
  colon_pattern <- "\\b([A-Za-z0-9\\.]+):::?"
  colon_matches <- gregexpr(colon_pattern, all_code, perl = TRUE)
  if (colon_matches[[1]][1] != -1) {
    m <- regmatches(all_code, colon_matches)[[1]]
    pkgs <- c(pkgs, sub(colon_pattern, "\\1", m, perl = TRUE))
  }
  unique(pkgs)
}

pkg_list <- unique(unlist(lapply(r_files, get_pkgs_from_file)))

# 3. Check installed versions
ip <- as.data.frame(installed.packages(), stringsAsFactors = FALSE)

result <- data.frame(
  Package = pkg_list,
  Version = ip[pkg_list, "Version"],
  stringsAsFactors = FALSE,
  row.names = NULL
)

# add CmdStan row
result <- rbind(
  result,
  data.frame(Package = "CmdStan", Version = cmdstanr::cmdstan_version())
)

# helper to get package website URL
get_pkg_url <- function(pkg) {
  # special cases
  url <- switch(pkg,
                brms = "https://paulbuerkner.com/brms/",
                CmdStan = "https://mc-stan.org/cmdstanr/",
                priorsense = "https://n-kall.github.io/priorsense/",
                NULL)
  if (!is.null(url)) return(url)

  # try DESCRIPTION first
  desc <- tryCatch(utils::packageDescription(pkg), error = function(e) NULL)
  if (!is.null(desc)) {
    if ("URL" %in% names(desc)) {
      url_field <- desc[["URL"]]
      if (!is.null(url_field) && nzchar(url_field)) {
        # DESCRIPTION may have multiple URLs separated by commas/spaces/newlines
        urls <- unlist(strsplit(url_field, "[,[:space:]]+"))
        urls <- urls[urls != ""]
        if (length(urls)) return(urls[1])
      }
    }
  }

  # fallback: CRAN page
  paste0("https://cran.r-project.org/package=", pkg)
}

# Build an HTML link for each package
result$Package_link <- vapply(
  result$Package,
  function(p) {
    url <- get_pkg_url(p)
    sprintf("<a href=\"%s\" target=\"_blank\">%s</a>", url, p)
  },
  character(1)
)

# Order and select columns for display
result_display <- result[order(result$Package), c("Package_link", "Version")]
names(result_display)[1] <- "Package"

result_display |>
  tinytable::tt(escape = FALSE) |>
  tinytable::theme_html(class = "tinytable tinytable-sm")
```
